# Generated by Django 5.0.1 on 2024-02-15 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Done'), (2, 'Doing'), (3, 'Undone')])),
            ],
        ),
    ]
